language: go
sudo: false
go_import_path: gopkg.in/go-oauth2/mysql.v3
go:
  - 1.9
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)